project:
  type: website
  output-dir: docs
  resources:
    - "projects/**"
    - "media/*"

website:
  title: "Josh Pearlson"
  favicon: media/jcp_logo2.png
  search:
    keyboard-shortcut: ["f"]
  navbar:
    logo: media/jcp_logo3.png
    right:
      - text: "Articles"
        href: articles/blog.qmd
      - text: "Projects"
        href: projects/projects.qmd
      - text: "About"
        href: aboutPage/about.qmd
format:
  html:
    theme:
      # cyborg
      # darkly
      slate
      # superhero
      # dark: darkly
      # light: cosmos
    css: css/header.css
    include-after-body: javaScript/console.html
